FROM node:latest AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:latest

COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

ENV PORT=80

EXPOSE ${PORT}

CMD ["nginx", "-g", "daemon off;"]