version: "3"
services:
    frontend:
        image: iddhi/library-system:frontend
        ports:
            - "5000:80"
        volumes:
            - /usr/src/app/node_modules
        environment:
            - NODE_ENV=development
            - PORT=80
            - VITE_PORT=http://localhost:3000
        stdin_open: true
        tty: true

    backend:
        image: iddhi/library-system:backend
        ports:
            - "3000:3000"
        volumes:
            - /usr/src/app/node_modules
        environment:
            - NODE_ENV=development
            - PORT=3000
            - DB=${DB:-mongodb://admin:password@database:27017/librarysystem}
        depends_on:
            - database
        networks:
            - mern-app
        stdin_open: true
        tty: true

    database:
        image: mongo:latest
        ports:
            - "27017:27017"
        networks:
            - mern-app
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password

networks:
    mern-app:
        driver: bridge
