name: Node.js Backend Automate Testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with: 
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Change Directory
      run: cd ./backend
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
